/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author duke
 */
public class SignInView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public SignInView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userText1 = new javax.swing.JLabel();
        userField1 = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        userField = new javax.swing.JTextField();
        passText = new javax.swing.JLabel();
        userText = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        bgLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userText1.setFont(new java.awt.Font("RocknRoll One", 0, 24)); // NOI18N
        userText1.setForeground(new java.awt.Color(255, 255, 255));
        userText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userText1.setText("Id");
        getContentPane().add(userText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 160, -1, -1));

        userField1.setBackground(new java.awt.Color(255, 255, 255));
        userField1.setFont(new java.awt.Font("RocknRoll One", 0, 18)); // NOI18N
        userField1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(userField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 190, 70, -1));

        passField.setBackground(new java.awt.Color(255, 255, 255));
        passField.setFont(new java.awt.Font("RocknRoll One", 0, 18)); // NOI18N
        passField.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 380, 350, -1));

        userField.setBackground(new java.awt.Color(255, 255, 255));
        userField.setFont(new java.awt.Font("RocknRoll One", 0, 18)); // NOI18N
        userField.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 280, 350, -1));

        passText.setFont(new java.awt.Font("RocknRoll One", 0, 24)); // NOI18N
        passText.setForeground(new java.awt.Color(255, 255, 255));
        passText.setText("Senha");
        getContentPane().add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 350, -1, -1));

        userText.setFont(new java.awt.Font("RocknRoll One", 0, 24)); // NOI18N
        userText.setForeground(new java.awt.Color(255, 255, 255));
        userText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userText.setText("Usuário");
        getContentPane().add(userText, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 250, -1, -1));

        saveButton.setBackground(new java.awt.Color(204, 204, 204));
        saveButton.setFont(new java.awt.Font("RocknRoll One", 0, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(0, 0, 0));
        saveButton.setText("Salvar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 460, 350, 40));

        bgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/LoginBg.png"))); // NOI18N
        getContentPane().add(bgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        LoginView loginView = new LoginView();
        loginView.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLogin;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passText;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField userField;
    private javax.swing.JTextField userField1;
    private javax.swing.JLabel userText;
    private javax.swing.JLabel userText1;
    // End of variables declaration//GEN-END:variables
}
